### ISSUE TITLE
Cperl-mode and highlight-refontification-list-extend-region-steps

### ISSUE THREAD

**Issue by CeleritasCelery** [Lindydancer/highlight-refontification#1]
I encountered your tool when you mentioned it in [this](http://emacs.stackexchange.com/questions/30807/cperl-mode-syntax-highlighting-breaks-when-inserting-a-newline-into-a-here-doc) question on StackOverflow. I took your advice and tried to use this package to understand how `cperl-mode` was highlighting the here doc's. However when ever I try to call  `highlight-refontification-list-extend-region-steps` inside of a here doc it hangs and I have to send `keyboard-quit` to get it to respond.  My extend region function is listed below. You can add it to `font-lock-extend-region-functions`. Any help you could provide as to why it is hanging would be greatly appreciated.
```
    (defun my/cperl-font-lock-extend-region-here ()
      (save-excursion
        (goto-char font-lock-beg)
        (when (re-search-backward "=<<\s*['\"]?[0-9a-zA-Z_]+['\"]?\s*;" nil t)
          (when (string-match "=<<\s*['\"]?\\([0-9a-zA-Z_]+\\)['\"]?\s*;" (thing-at-point 'line t))
            (let ((here-tag (concat "^" (match-string 1 (thing-at-point 'line t)) "$")))
              (forward-line 1)
              (let ((here-start (point)))
                (goto-char font-lock-end)
                (when (re-search-forward here-tag nil t)
                  (forward-line -1)
                  (end-of-line)
                  (setq font-lock-end (point))
                  (setq font-lock-beg here-start))))))))
 ```

**Comment by Lindydancer** [comment]
Hi!

I think the problem is that the functions in
`font-lock-extend-region-functions' are expected to return non-nil when
they have made a change, and nil when they haven't. It looks like your
function always return non-nil, when in a here-doc, since it ends with the
`setq' of `font-lock-beg'. See doc below:

  Special hook run just before proceeding to fontify a region.
  This is used to allow major modes to help font-lock find safe buffer
positions
  as beginning and end of the fontified region.  Its most common use is to
solve
  the problem of /identification/ of multiline elements by providing a
function
  that tries to find such elements and move the boundaries such that they do
  not fall in the middle of one.
  Each function is called with no argument; it is expected to adjust the
  dynamically bound variables `font-lock-beg' and `font-lock-end'; *and
return*
*  non-nil if it did make such an adjustment.*
*  These functions are run in turn repeatedly until they all return nil.*
  Put first the functions more likely to cause a change and cheaper to
compute.

One thing that puzzels me is that font-lock itself doesn't hang. Maybe it
checks that the borders were moved, and stops if they weren't. In that
case, my function should probably act the same way.

Thanks for using the package and for reporting this.

    -- Anders

**Comment by CeleritasCelery** [comment]
That addressed the problem with highlight-refontification hanging. Still didn't fix the problem in cperl HERE docs but thank you for the help.
